### ISSUE TITLE
Bypass don't work?

### ISSUE THREAD

**Issue by ghost** [HemanthJabalpuri/twrp_realme_RMX3195#1]
```
 ​#​ Bypass anti-rollback ROMs protection 
 ​#​ Set build date to Jan 1 2009 00:00:00 
 ​PRODUCT_PROPERTY_OVERRIDES​ += ​\ 
 ​    ro.build.date.utc=1230768000
```
Here I can see that you avoid a situation where TWRP will be replaced to a stock one. But after restarting to a system and then back in TWRP, this kind of situation happens.

**Using**: 3.6.0 release
**Device**: RMX3195

**Comment by HemanthJabalpuri** [comment]
Line that you quoted is for flashing older ROMs that check for date before installing and exit if it is newer.

As far as I know, replace of stock recovery is because of execution of /vendor/bin/[oppo-]install-recovery.sh

To stop this behaviour, you can use this Magisk module 
[RealmeRecoveryKeepV2.zip](https://github.com/HemanthJabalpuri/twrp_realme_RMX3195/files/8137509/RealmeRecoveryKeepV2.zip)


Thanks
